holidays = {
"01-jan":"Polar Bear Plunge Day",
"02-jan":"Buffet Day",
"03-jan":"Fruitcake Toss Day",
"04-jan":"Trivia Day",
"05-jan":"Bird Day",
"06-jan":"Bean Day",
"07-jan":"Old Rock Day",
"08-jan":"Earth's Rotation Day",
"09-jan":"Static Electricity Day",
"10-jan":"Cut Your Energy Costs Day",
"11-jan":"Learn Your Name in Morse Code Day",
"12-jan":"Marzipan Day",
"13-jan":"Make Your Dreams Come True Day",
"14-jan":"Organize Your Home Day",
"15-jan":"Strawberry Ice Cream Day",
"16-jan":"Nothing Day",
"17-jan":"Benjamin Franklin Day",
"18-jan":"Thesaurus Day",
"19-jan":"Tin Can Day",
"20-jan":"Penguin Awareness Day",
"21-jan":"Squirrel Appreciation Day",
"22-jan":"Hot Sauce Day",
"23-jan":"Handwriting Day",
"24-jan":"Compliment Day",
"25-jan":"Opposite Day",
"26-jan":"Spouse's Day",
"27-jan":"Chocolate Cake Day",
"28-jan":"Data Privacy Day",
"29-jan":"Puzzle Day",
"30-jan":"Croissant Day",
"31-jan":"Backwards Day",
"02-feb":"Day of the Crêpe",
"03-feb":"Carrot Cake Day",
"04-feb":"Thank Your Mailman Day",
"05-feb":"Work Naked Day",
"06-feb":"Eat Ice Cream for Breakfast Day",
"07-feb":"e-Day",
"08-feb":"Laugh and Get Rich Day",
"09-feb":"Toothache Day",
"10-feb":"Umbrella Day",
"11-feb":"Make a Friend Day",
"12-feb":"Darwin Day",
"13-feb":"World Radio Day",
"14-feb":"Ferris Wheel Day",
"15-feb":"Gumdrop Day",
"16-feb":"Do a Grouch a Favor Day",
"17-feb":"Random Act of Kindness Day",
"18-feb":"Battery Day",
"19-feb":"Chocolate Mint Day",
"22-feb":"Single Tasking Day",
"23-feb":"International Dog Biscuit Appreciation Day",
"24-feb":"Tortilla Chip Day",
"26-feb":"Pistachio Day",
"27-feb":"International Polar Bear Day",
"28-feb":"Public Sleeping Day",
"01-mar":"World Compliment Day",
"02-mar":"Old Stuff Day",
"03-mar":"I Want You to be Happy Day",
"04-mar":"March Forth and Do Something Day",
"05-mar":"Learn What Your Name Means Day",
"06-mar":"Dentist’s Day",
"07-mar":"Alexander Graham Bell Day",
"08-mar":"Proofreading Day",
"10-mar":"Mario Day",
"11-mar":"Oatmeal Nut Waffle Day",
"12-mar":"Alfred Hitchcock Day",
"13-mar":"Jewel Day",
"14-mar":"Pi Day",
"15-mar":"Napping Day",
"16-mar":"Every Thing You Do is Right Day",
"17-mar":"Submarine Day",
"18-mar":"Absolutely Incredible Kid Day",
"19-mar":"Let's Laugh Day",
"20-mar":"World Storytelling Day",
"21-mar":"Common Courtesy Day",
"22-mar":"International Goof Off Day",
"23-mar":"Puppy Day",
"24-mar":"Chocolate Covered Raisins Day",
"25-mar":"Waffle Day",
"26-mar":"Make Up Your Own Holiday Day",
"27-mar":"Spanish Paella Day",
"28-mar":"Something on a Stick Day",
"29-mar":"Smoke and Mirrors Day",
"30-mar":"Take a Walk in the Park Day",
"31-mar":"Bunsen Burner Day",
"01-apr":"Fun at Work Day",
"02-apr":"Walk to Work Day",
"03-apr":"World Party Day",
"04-apr":"Tell a Lie Day",
"05-apr":"Read a Road Map Day",
"06-apr":"Sorry Charlie Day",
"10-apr":"Siblings Day",
"11-apr":"Submarine Day",
"12-apr":"Grilled Cheese Day",
"13-apr":"Be Kind to Lawyers Day",
"14-apr":"International Moment of Laughter Day",
"16-apr":"Eggs Benedict Day",
"17-apr":"Haiku Poetry Day",
"18-apr":"Columnist Day",
"20-apr":"Look Alike Day",
"22-apr":"Jelly Bean Day",
"23-apr":"Take a Chance Day",
"25-apr":"DNA Day",
"26-apr":"Pretzel Day",
"29-apr":"Zipper Day",
"30-apr":"Honesty Day",
"01-may":"Batman Day",
"04-may":"Star Wars Day",
"06-may":"Beverage Day",
"07-may":"No Pants Day",
"09-may":"Europe Day",
"10-may":"Clean Up Your Room Day",
"11-may":"Twilight Zone Day",
"12-may":"National School Nurse Day",
"13-may":"Frog Jumping Day",
"14-may":"Dance Like a Chicken Day",
"15-may":"Chocolate Chip Day",
"17-may":"Pack Rat Day",
"18-may":"No Dirty Dishes Day",
"19-may":"May Ray Day",
"20-may":"Be a Millionaire Day",
"21-may":"Pizza Party Day",
"22-may":"Buy a Musical Instrument Day",
"24-may":"Scavenger Hunt Day",
"25-may":"Sing Out Day",
"26-may":"World Lindy Hop Day",
"27-may":"Sun Screen Day",
"28-may":"Hamburger Day",
"29-may":"Put a Pillow on Your Fridge Day",
"30-may":"My Bucket's Got a Hole Day",
"31-may":"Macaroon Day",
"01-jun":"Say Something Nice Day",
"02-jun":"Leave the Office Early Day",
"03-jun":"Repeat Day",
"04-jun":"Hug Your Cat Day",
"06-jun":"Drive-In Movie Day",
"07-jun":"VCR Day",
"08-jun":"Best Friends Day",
"09-jun":"Donald Duck Day",
"10-jun":"Iced Tea Day",
"11-jun":"Corn on the Cob Day",
"12-jun":"Red Rose Day",
"13-jun":"Sewing Machine Day",
"14-jun":"Bourbon Day",
"15-jun":"Nature Photography Day",
"16-jun":"Bloomsday",
"17-jun":"Eat Your Vegetables Day",
"18-jun":"International Picnic Day",
"19-jun":"World Juggling Day",
"21-jun":"Daylight Appreciation Day",
"22-jun":"Onion Ring Day",
"23-jun":"Typewriter Day",
"24-jun":"Swim a Lap Day",
"25-jun":"Take Your Dog to Work Day",
"26-jun":"Chocolate Pudding Day",
"27-jun":"Helen Keller Day",
"28-jun":"Tau Day",
"29-jun":"Camera Day",
"30-jun":"Meteor Watch Day",
"01-jul":"International Joke Day",
"02-jul":"I Forgot Day",
"03-jul":"Compliment Your Mirror Day",
"04-jul":"Sidewalk Egg Frying Day",
"05-jul":"Workaholics Day",
"06-jul":"World Kissing Day",
"07-jul":"Tell the Truth Day",
"08-jul":"Video Games Day",
"09-jul":"Sugar Cookie Day",
"10-jul":"Teddy Bears' Picnic Day",
"11-jul":"Cheer Up the Lonely Day",
"12-jul":"Simplicity Day",
"13-jul":"Embrace Your Geekness Day",
"14-jul":"Pandemonium Day",
"15-jul":"Gummi Worm Day",
"16-jul":"Corn Fritters Day",
"17-jul":"Yellow Pig Day",
"18-jul":"Insurance Nerd Day",
"19-jul":"Stick Out Your Tongue Day",
"20-jul":"Space Exploration Day",
"21-jul":"Junk Food Day",
"22-jul":"Pi Approximation Day",
"23-jul":"Vanilla Ice Cream Day",
"24-jul":"Cousins Day",
"25-jul":"Culinarians Day",
"26-jul":"Uncle and Aunt Day",
"27-jul":"Take your Pants for a Walk Day",
"28-jul":"Milk Chocolate Day",
"29-jul":"Lasagna Day",
"30-jul":"National Cheesecake Day",
"31-jul":"Uncommon Musical Instrument Day",
"01-aug":"National Girlfriend Day",
"02-aug":"Ice Cream Sandwich Day",
"03-aug":"Watermelon Day",
"04-aug":"Single Working Women's Day",
"05-aug":"Work Like a Dog Day",
"06-aug":"Fresh Breath Day",
"07-aug":"Lighthouse Day",
"08-aug":"Happiness Happens Day",
"09-aug":"Book Lovers Day",
"10-aug":"Lazy Day",
"11-aug":"Son and Daughter Day",
"12-aug":"Middle Child Day",
"13-aug":"Left-Handers Day",
"14-aug":"Creamsicle Day",
"15-aug":"Relaxation Day",
"16-aug":"Tell a Joke Day",
"17-aug":"Thrift Shop Day",
"18-aug":"Mail Order Catalog Day",
"19-aug":"World Photo Day",
"20-aug":"Chocolate Pecan Pie Day",
"21-aug":"Spumoni Day",
"22-aug":"Be An Angel Day",
"23-aug":"Ride Like the Wind Day",
"24-aug":"Pluto Demoted Day",
"25-aug":"Kiss and Make up Day",
"26-aug":"Dog Appreciation Day",
"27-aug":"The Duchess Who Wasn't Day",
"28-aug":"Bow Tie Day",
"29-aug":"According to Hoyle Day",
"30-aug":"Frankenstein Day",
"31-aug":"Eat Outside Day",
"01-sep":"Emma Nutt Day",
"02-sep":"Bison Ten Yell Day",
"03-sep":"Skyscraper Day",
"04-sep":"Eat an Extra Dessert Day",
"05-sep":"Be Late for Something Day",
"06-sep":"Fight Procrastination Day",
"07-sep":"Salami Day",
"08-sep":"Pardon Day",
"09-sep":"Teddy Bear Day",
"10-sep":"Swap Ideas Day",
"11-sep":"Make Your Bed Day",
"12-sep":"Chocolate Milkshake Day",
"13-sep":"Positive Thinking Day",
"14-sep":"Hug Your Hound Day",
"15-sep":"Make a Hat Day",
"16-sep":"Collect Rocks Day",
"17-sep":"International Country Music Day",
"18-sep":"National CleanUp Day",
"19-sep":"National Gymnastics Day",
"20-sep":"Punch Day",
"21-sep":"Miniature Golf Day",
"22-sep":"Hobbit Day",
"23-sep":"Checkers Day",
"24-sep":"Punctuation Day",
"25-sep":"Comic Book Day",
"26-sep":"Love Note Day",
"27-sep":"Crush a Can Day",
"28-sep":"Ask a Stupid Question Day",
"30-sep":"Hot Mulled Cider Day",
"01-oct":"International Coffee Day",
"02-oct":"Card Making Day",
"04-oct":"Taco Day",
"05-oct":"Chic Spy Day",
"06-oct":"Mad Hatter Day",
"07-oct":"Frappé Day",
"08-oct":"Pierogi Day",
"09-oct":"Curious Events Day",
"10-oct":"Handbag Day",
"11-oct":"It's My Party Day",
"12-oct":"Old Farmers Day",
"13-oct":"International Skeptics Day",
"15-oct":"I Love Lucy Day",
"16-oct":"Sweetest Day",
"17-oct":"Wear Something Gaudy Day",
"18-oct":"Chocolate Cupcake Day",
"20-oct":"International Sloth Day",
"21-oct":"Count your Buttons Day",
"22-oct":"Caps Lock Day",
"23-oct":"Mole Day",
"24-oct":"Bologna Day",
"25-oct":"Sourest Day",
"26-oct":"Howl at the Moon Day and Night",
"27-oct":"American Beer Day",
"28-oct":"International Animation Day",
"29-oct":"Internet Day",
"30-oct":"Candy Corn Day",
"31-oct":"Magic Day",
"01-nov":"Author's Day",
"02-nov":"Deviled Eggs Day",
"03-nov":"Sandwich Day",
"04-nov":"Common Sense Day",
"06-nov":"Saxophone Day",
"07-nov":"Zero Tasking Day",
"08-nov":"Tongue Twister Day",
"09-nov":"Chaos Never Dies Day",
"10-nov":"Forget Me Not Day",
"11-nov":"Origami Day",
"12-nov":"Happy Hour Day",
"13-nov":"World Kindness Day",
"14-nov":"Spicy Guacamole Day",
"15-nov":"Clean Out Your Refrigerator Day",
"16-nov":"Fast Food Day",
"17-nov":"Take A Hike Day",
"18-nov":"Push Button Phone Day",
"20-nov":"National Absurdity Day",
"21-nov":"World Hello Day",
"22-nov":"Go For a Ride Day",
"23-nov":"Fibonacci Day",
"24-nov":"Celebrate Your Unique Talent Day",
"25-nov":"Shopping Reminder Day",
"26-nov":"Cake Day",
"28-nov":"Red Planet Day",
"29-nov":"Electronic Greeting Card Day",
"30-nov":"Computer Security Day",
"01-dec":"Eat a Red Apple Day",
"02-dec":"Fritters Day",
"03-dec":"Make a Gift Day",
"04-dec":"Wear Brown Shoes Day",
"05-dec":"Day of the Ninja",
"06-dec":"Put on Your Own Shoes Day",
"07-dec":"Letter Writing Day",
"08-dec":"Pretend to Be a Time Traveler Day",
"09-dec":"Christmas Card Day",
"10-dec":"Dewey Decimal System Day",
"11-dec":"Noodle Ring Day",
"12-dec":"Gingerbread House Day",
"14-dec":"Monkey Day",
"16-dec":"Chocolate Covered Anything Day",
"17-dec":"Wright Brothers Day",
"20-dec":"Sangria Day",
"21-dec":"International Dalek Remembrance Day",
"22-dec":"Date Nut Bread Day",
"23-dec":"Festivus",
"24-dec":"Eggnog Day",
"25-dec":"Grav Mass Day",
"26-dec":"Thank You Note Day",
"27-dec":"No Interruptions Day",
"28-dec":"Card Playing Day",
"29-dec":"Pepper Pot Day",
"30-dec":"Bicarbonate of Soda Day",
"31-dec":"Make Up Your Mind Day"
}
